config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path:'' ,path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios ,except: [:show] ##except show的意思就是把show的route獨立出來寫
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'angular-items', to: 'portfolios#angular'
  
  get 'about', to: 'page#about' 
  get 'contact', to: 'page#contact'

  resources :blogs do
  	member do
  		get :toggle_status
  	end
  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #root -> localhost:3000
  root to: 'page#home'
end

app/models/blog.rb
class Blog < ApplicationRecord
	enum status: {draft: 0 ,published: 1 }
	paginates_per 2
	extend FriendlyId
	friendly_id :title , use: :slugged

	validates_presence_of :title, :body

	belongs_to :topic


end
  

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  access all: [:show, :index], user: {except: [:destroy, :new , :create , :edit, :update]}, site_admin: :all


  layout "blog"

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.order(:created_at).page(params[:page])
    ## byebug
    ## puts "**"
    ## puts @blogs.inspect
    ## puts "**"
    @page_title ="My blogs website" 
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @page_title = @blog.title
    @seo_keyword = @blog.body
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end 

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status 
    if @blog.draft?
      @blog.published!
    else
      @blog.draft!
    end
    redirect_to blogs_url,notice: 'Posts status has been updated.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<h2 class="blog-post-title"><%= blog.title.upcase %></h2>
<p class="blog-post-meta">Pubilshed   <%= distance_of_time_in_words(blog.created_at,Time.now)%> ago </p>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <%= link_to 'Show', blog ,class: 'breadcrumb-item' %>
    <%= link_to 'Edit', edit_blog_path(blog),class: 'breadcrumb-item' if logged_in?(:site_admin) %>
    <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } ,class: 'breadcrumb-item' if logged_in?(:site_admin)  %></a>
    <%= link_to blog.status, toggle_status_blog_path(blog),class: 'breadcrumb-item' if logged_in?(:site_admin)  %>
  </ol>
</nav>
<p><%= blog.body %></p>

<hr>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title , class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, id: :blog_body, class: 'form-control' , rows: 20 %>
  </div>

  <div class="form-group">
    <%= form.label :topic_id %>
    
    <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Small button
    </button>
    <div class="dropdown-menu">
      <%= form.text_area :topic_id, id: :topic_id , class: 'dropdown-item'%>
    </div>
  </div>

  <div class="actions">
    <%= form.submit "Sumbit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-md-8">
	<h2 class="blog-post-title">Editing Blog</h2>


<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/index.html.erb
  <div class="col-md-8 blog-main">
    <h3 class="pb-4 mb-4 font-italic border-bottom">
        knowledge is power
    </h3>
    <%= link_to 'New Blog', new_blog_path if logged_in?(:site_admin) %>
    <div class="blog-post">

        <%= render @blogs %>
    </div>

      <nav class="blog-pagination">
        <%= paginate @blogs %>

      </nav>
  </div>

app/views/blogs/new.html.erb
<div class="col-md-8">
	<h2 class="blog-post-title">New Blog</h2>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<div class="col-md-8">
	<h2 class="blog-post-title"><%= @blog.title.upcase %></h2>

<p><%= @blog.body %></p>

<ol>
	<il><%= link_to 'Edit', edit_blog_path(@blog) %> | <%= link_to 'Back', blogs_path %></il>
</ol>
</div>