config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path:'' ,path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios ,except: [:show] ##except show的意思就是把show的route獨立出來寫
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'angular-items', to: 'portfolios#angular'
  
  get 'about', to: 'page#about' 
  get 'contact', to: 'page#contact'

  resources :blogs do
  	member do
  		get :toggle_status
  	end
  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #root -> localhost:3000
  root to: 'page#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
	has_many :technologies 
	accepts_nested_attributes_for :technologies, 
	                              reject_if: lambda { |attrs| attrs['name'].blank? }

	validates_presence_of :title, :body

	paginates_per 9

	mount_uploader :thumb_image, PorfolioUploader
	mount_uploader :main_image, PorfolioUploader

	def self.angular
		where(subtitle: 'Angular')
	end

	scope :ruby_on_rails_portfolio_items, -> {where(subtitle: 'Ruby on rails')}

	#after_initialize :set_defaults

	#在create之後，系統會自動產生main與thumb的預設

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  access all: [:show, :index, :angular], user: {except: [:destroy, :new , :create , :edit, :update]}, site_admin: :all

  layout "portfolio"

	def index
		@portfolio_items = Portfolio.order(:created_at).page(params[:page])

    @page_title ="My porttfolio website" 
	end

  def angular
    @angular_portfolio_item = Portfolio.angular
  end 

	def new
		@portfolio_item = Portfolio.new

    3.times { @portfolio_item.technologies.build }
	end 

	def create 
		@portfolio_item = Portfolio.new(portfolio_params)

    	respond_to do |format|
      	if @portfolio_item.save
        	format.html { redirect_to portfolios_path, notice: 'Portfolio item was successfully created.' }
      	else
        	format.html { render :new }
      	end
    	end 
	end 

	def edit
		@portfolio_item = Portfolio.find(params[:id])

    3.times { @portfolio_item.technologies.build }
	end

	def update
		@portfolio_item = Portfolio.find(params[:id])
		respond_to do |format|
      		if @portfolio_item.update(portfolio_params)
        		format.html { redirect_to portfolios_path, notice: 'Blog was successfully updated.' }
      		else
       		 	format.html { render :edit } 
      		end 
    	end
	end

	def show
		@portfolio_item = Portfolio.find(params[:id])
	end

  def destroy
  	#perform the lookup 
  	@portfolio_item = Portfolio.find(params[:id])

  	#Destry/delete the record
    @portfolio_item.destroy 

    #Redirect
    respond_to do |format|
      format.html { redirect_to portfolios_path, notice: 'Portfolio item was successfully destroyed.' }
    end
  end

  private
  def portfolio_params
    params.require(:portfolio).permit(:title, 
                                      :subtitle, 
                                      :body , 
                                      :thumb_image,
                                      :main_image,
                                      technologies_attributes: [:name])
  end 
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
	def image_generator(height:,width:)
		"https://via.placeholder.com/#{height}X#{width}.png?"
	end

	def portfolio_img img,type
		if img.model.main_image? || img.model.thumb_image?
			img
		elsif type == 'thumb'
			image_generator(height: '350' ,width: '200')
		elsif type == 'main'
			image_generator(height: '600' ,width: '400')
		end
			
	end
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>


  <div class= "row" >
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: 'form-control'  %>
      </div>   

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a main image file
          <%= f.file_field :main_image , style: 'display:none;' %>
        </label>
      </div> 

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a thumb image file
          <%= f.file_field :thumb_image , style: 'display:none;' %>
        </label>
      </div> 

      <div class="form-group">
      </div> 
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control' , rows: 20  %>
      </div>
    </div>
  </div>

  <hr>
  <div class="col-md-12">
    <h2>Technologies Uesd:</h2>
    <div>
      <%= f.fields_for  :technologies do |technologies_form| %>
        <div class="form-group">
          <%= technologies_form.label :name %>
          <%= technologies_form.text_area :name , class: 'form-control' %>
        </div>
      <% end  %> 
    </div>    
  </div>

  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4">
    <div class="card mb-4 shadow-sm">
        <%= image_tag portfolio_img(portfolio_item.thumb_image,'thumb') ,width: "350", height: "350" %>
        <div class="card-body">
        	<p class="card-text"><%= link_to portfolio_item.title ,portfolio_show_path(portfolio_item) %></p>
            <p class="card-text"><%= portfolio_item.subtitle %>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                	<% if logged_in?(:site_admin) %>
						<%= link_to "Edit",edit_portfolio_path(portfolio_item.id), data: { confirm: 'Are you sure?' },class: 'btn btn-sm btn-outline-secondary'  %>
						<%= link_to 'Destroy', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } ,class: 'btn btn-sm btn-outline-secondary' %>
					<% end %>
                </div>
                <small class="text-muted">9 mins</small>
            </div>
        </div>
    </div>
</div>

app/views/portfolios/angular.html.erb
 <h1>Angular Portfolio Items</h1>


<%= link_to "Create a new Portfolio",new_portfolio_url if logged_in?(:site_admin) %>

<% @angular_portfolio_item .each do |portfolio_item| %>
	<p><%= link_to portfolio_item.title ,portfolio_show_path(portfolio_item) %></p>
	<p><%= portfolio_item.subtitle %></p>
	<p><%= portfolio_item.body %></p>
	<a><%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %></a>
	 
	<%= link_to "Edit",edit_portfolio_path(portfolio_item.id), data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
	<%= link_to 'Destroy', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
	<h1>Edit this Portfolio item</h1>

	<%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
  <div class="album py-5 bg-light">
    <div class="container">
    	<h1>Portfolio Items</h1>
    	<% if logged_in?(:site_admin) %>
    		<%= link_to "Create a new Portfolio",new_portfolio_url, class: 'btn btn-outline-success' %>
    	<% end %>
    	<hr>
      <div class="row sortable">
			   <%= render partial:'portfolio_item' ,collection: @portfolio_items %>
      </div>

      <%= paginate @portfolio_items %>
    </div>
  </div>
 

app/views/portfolios/new.html.erb
<h1>Create a new Portfolio item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/show.html.erb
<div class = "container portfolio-container">
	<div class="row">
		 <div class="col-md-7">
		 	<%= image_tag portfolio_img(@portfolio_item.main_image,'main') ,width: "100%" %>
		 </div>
		 <div class="col-md-5">
		 	<h1><%= @portfolio_item.title %></h1>
			<em><%= @portfolio_item.subtitle %></em>
			<p><%= @portfolio_item.body %></p>

			<h2>Technologies Use:</h2>
			<% @portfolio_item.technologies.each do |t| %>
				<p><%= t.name %></p>
			<% end %>
		 </div>
	</div>
</div>








 


 
 