config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path:'' ,path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios ,except: [:show] ##except show的意思就是把show的route獨立出來寫
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'angular-items', to: 'portfolios#angular'
  
  get 'about', to: 'page#about' 
  get 'contact', to: 'page#contact'

  resources :blogs do
  	member do
  		get :toggle_status
  	end
  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #root -> localhost:3000
  root to: 'page#home'
end

app/views/shared/_application_footer.html.erb
 <footer class="mastfoot mt-auto">
    <div class="inner app-footer">
        <p>@2019 |  wendyyao All rights reserve </a>.</p>
    </div>
</footer>

app/views/shared/_application_nav.html.erb
  <header class="masthead mb-auto">
    <div class="inner">
      <h3 class="masthead-brand">Wendyyao</h3>
      <nav class="nav nav-masthead justify-content-center app-nav">
          <%= nav_helper 'nav-link','span' %>
          <%= login_helper 'nav-link' %>
      </nav>
    </div>
  </header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>Blog built for wendyyao</p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_nav.html.erb
  <div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
          <%= nav_helper 'nav-link','span' %>
          <%= login_helper 'nav-link' %>
      </nav>
  </div>

app/views/shared/_blog_silde.html.erb
<aside class="col-md-4 blog-sidebar">
  <div class="p-4 mb-3 bg-light rounded">
    <h4 class="font-italic">About</h4>
    <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>

  <div class="p-4">
    <h4 class="font-italic">Archives</h4>
    <ol class="list-unstyled mb-0">
      <li><a href="#">March 2020</a></li>
      <li><a href="#">February 2020</a></li>
      <li><a href="#">January 2020</a></li>
      <li><a href="#">December 2019</a></li>
      <li><a href="#">November 2019</a></li>
    </ol>
  </div>

      <div class="p-4">
        <h4 class="font-italic">Elsewhere</h4>
        <ol class="list-unstyled scioal-link">
          <li><a href="https://github.com/a151815058"><%= fa_icon "github" %></a></li>
          <li><a href="https://www.facebook.com/profile.php?id=100005253814721&ref=bookmarks"><%= fa_icon "facebook" %></a></li>
        </ol>
      </div>
    </aside><!-- /.blog-sidebar -->

app/views/shared/_nav.html.erb
 <div class="<%= loacation %>">
    <%= nav_helper 'nav-link','span' %>
</div>

app/views/shared/_portfolio_header.html.erb
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Navigation</h4>
          <ul class="list-unstyled">
            <li><%= link_to "Home", root_path ,class: 'text-white' %></li>
            <li><%= link_to "About", about_path,class: 'text-white' %></li>
            <li><%= link_to "Contact", contact_path,class: 'text-white' %></li>
            <li><%= link_to "Blog", blogs_path,class: 'text-white' %></li>
            <li><%= link_to "Portfolio ", portfolios_path,class: 'text-white' %></li>
            <li><%= login_helper 'text-white' %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="/portfolios" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Wendyyao</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>

app/views/shared/_portfolio_nav.html.erb
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Navigation</h4>
          <ul class="list-unstyled">
            <%= nav_helper 'text-white','li' %>
            <li><%= login_helper 'text-white' %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="/portfolios" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Wendyyao</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>

app/views/shared/_portfolio_subscribe.html.erb
  <section class="jumbotron text-center">
    <div class="container">
      <h1>My Portfolio</h1>
      <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
      <p>
        <%= link_to 'Find Out About Me',about_path , class: 'btn btn-primary my-2' %>
        <%= link_to 'My Blog ',blogs_path , class: 'btn btn-light my-2' %>
      </p>
    </div>
  </section>